### ISSUE TITLE
minor edits to Team page

### ISSUE THREAD

**Issue by nlharris** [monarch-initiative/monarch-ui#474]
On https://monarchinitiative.org/about/team:
Hary -> Harry

Also, in the LBNL section, Harry is listed after the alumni, and his image is broken. You can find a photo of Harry here: https://berkeleybop.github.io/people/harry-caufield/

(Several other people have broken images as well)

need to update:
> Charité - Universitätsmedizin Berlin
> Sebastian Köhler

**Comment by vincerubinetti** [comment]
This was already caught and fixed in the new monarch ui. I've transferred this issue to the old (current) ui in case anyone wants to do a temporary fix.

**Comment by nlharris** [comment]
https://monarchinitiative.org/about/team still shows the errors i noticed -- when will the fixes to the new ui propagate to it?

**Comment by nlharris** [comment]
The live site still shows the old, incorrect team page (which is at https://github.com/monarch-initiative/monarch-ui/blob/master/public/team.yaml).

**Comment by nlharris** [comment]
The participating institutions at the top needs to have a lot of them demoted to "(past)".

The CU team member list isn't completely up to date.

There are broken images, like this:
<img width="374" alt="Screen Shot 2022-08-11 at 6 14 22 PM" src="https://user-images.githubusercontent.com/348704/184267447-05c8134d-4246-4fe4-b36d-231e88538891.png">
<img width="428" alt="Screen Shot 2022-08-11 at 6 14 13 PM" src="https://user-images.githubusercontent.com/348704/184267454-7e3c944e-27ad-4ac5-ae49-c8335c9b0b84.png">

**Comment by vincerubinetti** [comment]
There are indeed a whole host of errors on this page and elsewhere. I believe they are all fixed on the new UI. Could you verify this?

https://monarch-ui-new.monarchinitiative.org/team

If it's all correct, maybe we could just link to the new page for a fixed/updated team list.

**Comment by nlharris** [comment]
that's better, though there are still things that are out of date. for example, seb is not at charite; nico is not at EBI. kent is listed under CU; didn't he leave before the move to CU? (i could be wrong about that one.)

i like how the alumni have their little time icons, but it seems weird to me to list them -- with photos! -- along with the current members. i would move them to the bottom and not include photos.

**Comment by monicacecilia** [comment]
Dear @vincerubinetti I updated the Team Page with latest details (updated some alumni and some titles, added new institutions, added links, changed order of institutions, etc.). 

I do agree with Nomi regarding putting all alumni in some group. We could group all of them under a generic 'Alumni members' list at the bottom, instead of including them under their respective institutions. That would probably be better. Would that be possible?

I know we also have alumni institutions... so perhaps we remove the affiliations from the list of Alumni?

Please let me know if you have a better suggestion. Thank you very much!

**Comment by nlharris** [comment]
https://monarchinitiative.org/about/team still shows the old, buggy version (e.g. "Hary") of the Team page. Can we switch to the new page on the public site?

**Comment by nlharris** [comment]
I guess this is obsolete because the new site is different, and the issues seem to have been addressed. Should I close this?

**Comment by glass-ships** [comment]
@nlharris There's an active issue for updating the Team page on the new version of the website (https://github.com/monarch-initiative/monarch-app/issues/259) 

It would actually be super helpful if you (or someone) could take a look at the latest version at https://monarch-app.monarchinitiative.org/team and if there are any glaring issues/changes which need addressing, let us know via the new issue?

**Comment by glass-ships** [comment]
Awesome, thanks! Yeah, I think this one's safe to close
